# application.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oldies_but_goodies?useSSL=false&allowPublicKeyRetrieval=true&useLegacyAuth=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db_username}
    password: ${db_password}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail_username}
    password: ${mail_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: false

  data:
    redis:
      host: ${rds_host}
      port: ${rds_port}
      password: ${rds_password}
      username: ${rds_username}
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao_client_id}
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            scope: profile_nickname, account_email, profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: ${jwt_secret}
  expiration: 3600000