# application.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oldies_but_goodies?useSSL=false&allowPublicKeyRetrieval=true&useLegacyAuth=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db.username}
    password: ${db.password}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: create-drop


redis:
  host: ${rds.host}
  port: ${rds.port}
  password: ${rds.pwd}